// <auto-generated />
using System;
using CfNCKH.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CfNCKH.Data.Migrations
{
    [DbContext(typeof(CfCRMNCKHv02Context))]
    [Migration("20250204024209_khoi_createDb")]
    partial class khoi_createDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CfNCKH.Data.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("DOB");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "idx_Account_Email");

                    b.HasIndex(new[] { "RoleId" }, "idx_Account_RoleId");

                    b.HasIndex(new[] { "Username" }, "idx_Account_Username");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.AccountActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("ActivityCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AccountId" }, "idx_AccountActivity_AccountId");

                    b.HasIndex(new[] { "CreatedTime" }, "idx_AccountActivity_CreatedTime");

                    b.ToTable("AccountActivity", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("WorkHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.CashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AccountId" }, "idx_CashFlow_AccountId");

                    b.HasIndex(new[] { "CreatedTime" }, "idx_CashFlow_CreatedTime");

                    b.ToTable("CashFlow", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DebtCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DebtName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsPaId")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaIdAt")
                        .HasColumnType("datetime");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Debt", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("DishCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DishCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DishCategoryId" }, "idx_Dish_DishCategoryId");

                    b.HasIndex(new[] { "DishCode" }, "idx_Dish_DishCode");

                    b.ToTable("Dish", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.DishCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DishCategoryCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DishCateogryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DishCategoryCode" }, "idx_DishCategory_DishCategoryCode");

                    b.ToTable("DishCategory", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.DishOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("DishOrderStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishOrderStatusId");

                    b.HasIndex("TableId");

                    b.ToTable("DishOrder", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.DishOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("DishOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("DishOrderId");

                    b.ToTable("DishOrderDetail", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.DishOrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DishOrderStatusCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DishOrderStatusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("DishOrderStatus", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.FinancialTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Period")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TargetProfit")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TargetRevenue")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.ToTable("FinancialTarget", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal?>("AveragePrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("IngredientCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("IngredientCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SelfLife")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientCategoryId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UnitId");

                    b.ToTable("Ingredient", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.IngredientCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("IngredientCategoryCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IngredientCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("IngredientCategory", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.InventoryAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("AuditCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Auditor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("InventoryAudit", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.InventoryDiscrepancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("ActualQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DiscrepancyReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ExpectedQuantity")
                        .HasColumnType("int");

                    b.Property<int>("InventoryAuditId")
                        .HasColumnType("int");

                    b.Property<int>("StockLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryAuditId");

                    b.HasIndex("StockLevelId");

                    b.ToTable("InventoryDiscrepancy", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("InvoiceCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalGuest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AccountId" }, "idx_Invoice_AccountId");

                    b.HasIndex(new[] { "CreatedTime" }, "idx_Invoice_CreatedTime");

                    b.HasIndex(new[] { "InvoiceCode" }, "idx_Invoice_InvoiceCode");

                    b.HasIndex(new[] { "TableId" }, "idx_Invoice_TableId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PurchaseOrderCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("PurchaseOrder", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetail", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleCode" }, "idx_Role_RoleCode");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.StockLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockLevel", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StockTransactionCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockTransaction", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.StockTransactionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockLevelId")
                        .HasColumnType("int");

                    b.Property<int>("StockTransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StockLevelId");

                    b.HasIndex("StockTransactionId");

                    b.ToTable("StockTransactionDetail", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("SupplierCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("TableCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TableStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TableCode" }, "idx_Table_TableCode");

                    b.HasIndex(new[] { "TableStatus" }, "idx_Table_TableStatus");

                    b.ToTable("Table", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.TableBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("CheckinTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AccountId" }, "idx_TableBooking_AccountId");

                    b.HasIndex(new[] { "BookingTime" }, "idx_TableBooking_BookingTime");

                    b.HasIndex(new[] { "TableId" }, "idx_TableBooking_TableId");

                    b.ToTable("TableBooking", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Unit", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Warehouse", (string)null);
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Account", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Account__RoleId__02FC7413");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.AccountActivity", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Account", "Account")
                        .WithMany("AccountActivities")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__AccountAc__Accou__03F0984C");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Attendance", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Account", "Account")
                        .WithMany("Attendances")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK__Attendanc__Accou__04E4BC85");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.CashFlow", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Account", "Account")
                        .WithMany("CashFlows")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__CashFlow__Accoun__05D8E0BE");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Debt", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Supplier", "Supplier")
                        .WithMany("Debts")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK__Debt__SupplierId__06CD04F7");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Dish", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.DishCategory", "DishCategory")
                        .WithMany("Dishes")
                        .HasForeignKey("DishCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Dish__DishCatego__07C12930");

                    b.Navigation("DishCategory");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.DishOrder", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.DishOrderStatus", "DishOrderStatus")
                        .WithMany("DishOrders")
                        .HasForeignKey("DishOrderStatusId")
                        .IsRequired()
                        .HasConstraintName("FK__DishOrder__DishO__08B54D69");

                    b.HasOne("CfNCKH.Data.Models.Table", "Table")
                        .WithMany("DishOrders")
                        .HasForeignKey("TableId")
                        .IsRequired()
                        .HasConstraintName("FK__DishOrder__Table__09A971A2");

                    b.Navigation("DishOrderStatus");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.DishOrderDetail", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Dish", "Dish")
                        .WithMany("DishOrderDetails")
                        .HasForeignKey("DishId")
                        .IsRequired()
                        .HasConstraintName("FK__DishOrder__DishI__0A9D95DB");

                    b.HasOne("CfNCKH.Data.Models.DishOrder", "DishOrder")
                        .WithMany("DishOrderDetails")
                        .HasForeignKey("DishOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__DishOrder__DishO__0B91BA14");

                    b.Navigation("Dish");

                    b.Navigation("DishOrder");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Ingredient", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.IngredientCategory", "IngredientCategory")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingredien__Ingre__0C85DE4D");

                    b.HasOne("CfNCKH.Data.Models.Supplier", "Supplier")
                        .WithMany("Ingredients")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingredien__Suppl__0D7A0286");

                    b.HasOne("CfNCKH.Data.Models.Unit", "Unit")
                        .WithMany("Ingredients")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingredien__UnitI__0E6E26BF");

                    b.Navigation("IngredientCategory");

                    b.Navigation("Supplier");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.InventoryDiscrepancy", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.InventoryAudit", "InventoryAudit")
                        .WithMany("InventoryDiscrepancies")
                        .HasForeignKey("InventoryAuditId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Inven__0F624AF8");

                    b.HasOne("CfNCKH.Data.Models.StockLevel", "StockLevel")
                        .WithMany("InventoryDiscrepancies")
                        .HasForeignKey("StockLevelId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventory__Stock__10566F31");

                    b.Navigation("InventoryAudit");

                    b.Navigation("StockLevel");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Invoice", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Account", "Account")
                        .WithMany("Invoices")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__Invoice__Account__114A936A");

                    b.HasOne("CfNCKH.Data.Models.Table", "Table")
                        .WithMany("Invoices")
                        .HasForeignKey("TableId")
                        .IsRequired()
                        .HasConstraintName("FK__Invoice__TableId__123EB7A3");

                    b.Navigation("Account");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.PurchaseOrder", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Account", "Account")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseO__Accou__1332DBDC");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.PurchaseOrderDetail", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Ingredient", "Ingredient")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseO__Ingre__14270015");

                    b.HasOne("CfNCKH.Data.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderDetails")
                        .HasForeignKey("PurchaseOrderId")
                        .IsRequired()
                        .HasConstraintName("FK__PurchaseO__Purch__151B244E");

                    b.Navigation("Ingredient");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.StockLevel", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Ingredient", "Ingredient")
                        .WithMany("StockLevels")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK__StockLeve__Ingre__160F4887");

                    b.HasOne("CfNCKH.Data.Models.Warehouse", "Warehouse")
                        .WithMany("StockLevels")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK__StockLeve__Wareh__17036CC0");

                    b.Navigation("Ingredient");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.StockTransaction", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Account", "Account")
                        .WithMany("StockTransactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__StockTran__Accou__17F790F9");

                    b.HasOne("CfNCKH.Data.Models.Warehouse", "Warehouse")
                        .WithMany("StockTransactions")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("FK__StockTran__Wareh__18EBB532");

                    b.Navigation("Account");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.StockTransactionDetail", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.StockLevel", "StockLevel")
                        .WithMany("StockTransactionDetails")
                        .HasForeignKey("StockLevelId")
                        .IsRequired()
                        .HasConstraintName("FK__StockTran__Stock__19DFD96B");

                    b.HasOne("CfNCKH.Data.Models.StockTransaction", "StockTransaction")
                        .WithMany("StockTransactionDetails")
                        .HasForeignKey("StockTransactionId")
                        .IsRequired()
                        .HasConstraintName("FK__StockTran__Stock__1AD3FDA4");

                    b.Navigation("StockLevel");

                    b.Navigation("StockTransaction");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.TableBooking", b =>
                {
                    b.HasOne("CfNCKH.Data.Models.Account", "Account")
                        .WithMany("TableBookings")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK__TableBook__Accou__1BC821DD");

                    b.HasOne("CfNCKH.Data.Models.Table", "Table")
                        .WithMany("TableBookings")
                        .HasForeignKey("TableId")
                        .IsRequired()
                        .HasConstraintName("FK__TableBook__Table__1CBC4616");

                    b.Navigation("Account");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Account", b =>
                {
                    b.Navigation("AccountActivities");

                    b.Navigation("Attendances");

                    b.Navigation("CashFlows");

                    b.Navigation("Invoices");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("StockTransactions");

                    b.Navigation("TableBookings");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Dish", b =>
                {
                    b.Navigation("DishOrderDetails");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.DishCategory", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.DishOrder", b =>
                {
                    b.Navigation("DishOrderDetails");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.DishOrderStatus", b =>
                {
                    b.Navigation("DishOrders");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Ingredient", b =>
                {
                    b.Navigation("PurchaseOrderDetails");

                    b.Navigation("StockLevels");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.IngredientCategory", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.InventoryAudit", b =>
                {
                    b.Navigation("InventoryDiscrepancies");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderDetails");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.StockLevel", b =>
                {
                    b.Navigation("InventoryDiscrepancies");

                    b.Navigation("StockTransactionDetails");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.StockTransaction", b =>
                {
                    b.Navigation("StockTransactionDetails");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Supplier", b =>
                {
                    b.Navigation("Debts");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Table", b =>
                {
                    b.Navigation("DishOrders");

                    b.Navigation("Invoices");

                    b.Navigation("TableBookings");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Unit", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CfNCKH.Data.Models.Warehouse", b =>
                {
                    b.Navigation("StockLevels");

                    b.Navigation("StockTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
